### ISSUE TITLE
uvccamera报错， 1080P是可以支持的，但是报错了

### ISSUE THREAD

**Issue by swallowsonny** [MrXRain/CameraFrameWork#1]
E/AndroidRuntime: FATAL EXCEPTION: USBMonitor
    Process: com.terminus.framework, PID: 29292
    java.lang.IllegalArgumentException: Failed to set preview size
        at com.serenegiant.usb.UVCCamera.setPreviewSize(UVCCamera.java:328)
        at com.serenegiant.usb.UVCCamera.setPreviewSize(UVCCamera.java:299)
        at com.core.camera.uvc.Camera3.applyCameraParam(Camera3.java:102)
        at com.core.camera.uvc.Camera3.access$500(Camera3.java:24)
        at com.core.camera.uvc.Camera3$1.onConnect(Camera3.java:77)
        at com.serenegiant.usb.USBMonitor$3.run(USBMonitor.java:574)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by MrXRain** [comment]
根据日志记录显示，参数错误，可能是宽高参数不匹配导致
